"""
Pydantic AE5<K
"""
from app.schemas.backtest import (
    BacktestConfig,
    BacktestListItem,
    BacktestListResponse,
    BacktestMetrics,
    BacktestResult,
    BacktestRunRequest,
    BacktestRunResponse,
    EquityCurvePoint,
    Trade,
)
from app.schemas.indicator import (
    IndicatorCalculateRequest,
    IndicatorCalculateResponse,
    IndicatorConfig,
    IndicatorInfo,
    IndicatorListResponse,
    IndicatorParameter,
    IndicatorValue,
    MultiTimeframeIndicatorConfig,
)
from app.schemas.instrument import (
    IndexBase,
    IndexCreate,
    IndexRead,
    IndexUpdate,
    IndexWithInstruments,
    InstrumentBase,
    InstrumentCreate,
    InstrumentRead,
    InstrumentUpdate,
    InstrumentWithIndex,
)
from app.schemas.ohlcv import (
    OHLCVBase,
    OHLCVBulkCreate,
    OHLCVCreate,
    OHLCVImportRequest,
    OHLCVQuery,
    OHLCVRead,
    TimeframeList,
)
from app.schemas.signal import (
    SignalBase,
    SignalCreate,
    SignalGenerateRequest,
    SignalGenerateResponse,
    SignalQuery,
    SignalRead,
    SignalStatistics,
    SignalWithInstrument,
)
from app.schemas.strategy import (
    StrategyBase,
    StrategyConfig,
    StrategyCreate,
    StrategyDetails,
    StrategyIndicator,
    StrategyListItem,
    StrategyListResponse,
    StrategyRead,
    StrategyRule,
    StrategyUpdate,
    StrategyValidation,
)

__all__ = [
    # Instrument schemas
    "InstrumentBase",
    "InstrumentCreate",
    "InstrumentUpdate",
    "InstrumentRead",
    "InstrumentWithIndex",
    "IndexBase",
    "IndexCreate",
    "IndexUpdate",
    "IndexRead",
    "IndexWithInstruments",
    # OHLCV schemas
    "OHLCVBase",
    "OHLCVCreate",
    "OHLCVRead",
    "OHLCVQuery",
    "OHLCVBulkCreate",
    "OHLCVImportRequest",
    "TimeframeList",
    # Signal schemas
    "SignalBase",
    "SignalCreate",
    "SignalRead",
    "SignalWithInstrument",
    "SignalQuery",
    "SignalGenerateRequest",
    "SignalGenerateResponse",
    "SignalStatistics",
    # Indicator schemas
    "IndicatorParameter",
    "IndicatorInfo",
    "IndicatorConfig",
    "IndicatorCalculateRequest",
    "IndicatorCalculateResponse",
    "IndicatorValue",
    "IndicatorListResponse",
    "MultiTimeframeIndicatorConfig",
    # Strategy schemas
    "StrategyBase",
    "StrategyConfig",
    "StrategyCreate",
    "StrategyUpdate",
    "StrategyRead",
    "StrategyDetails",
    "StrategyListItem",
    "StrategyListResponse",
    "StrategyIndicator",
    "StrategyRule",
    "StrategyValidation",
    # Backtest schemas
    "BacktestConfig",
    "Trade",
    "EquityCurvePoint",
    "BacktestMetrics",
    "BacktestResult",
    "BacktestRunRequest",
    "BacktestRunResponse",
    "BacktestListItem",
    "BacktestListResponse",
]
